// Code generated by protoc-gen-go.
// source: pb/pb.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	pb/pb.proto

It has these top-level messages:
	MinionConfig
	Reply
	Request
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type MinionConfig_Role int32

const (
	MinionConfig_NONE   MinionConfig_Role = 0
	MinionConfig_WORKER MinionConfig_Role = 1
	MinionConfig_MASTER MinionConfig_Role = 2
)

var MinionConfig_Role_name = map[int32]string{
	0: "NONE",
	1: "WORKER",
	2: "MASTER",
}
var MinionConfig_Role_value = map[string]int32{
	"NONE":   0,
	"WORKER": 1,
	"MASTER": 2,
}

func (x MinionConfig_Role) String() string {
	return proto.EnumName(MinionConfig_Role_name, int32(x))
}
func (MinionConfig_Role) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type MinionConfig struct {
	ID        string            `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
	Role      MinionConfig_Role `protobuf:"varint,2,opt,name=role,enum=MinionConfig_Role" json:"role,omitempty"`
	PrivateIP string            `protobuf:"bytes,3,opt,name=PrivateIP" json:"PrivateIP,omitempty"`
	EtcdToken string            `protobuf:"bytes,4,opt,name=EtcdToken" json:"EtcdToken,omitempty"`
	Spec      string            `protobuf:"bytes,5,opt,name=Spec" json:"Spec,omitempty"`
}

func (m *MinionConfig) Reset()                    { *m = MinionConfig{} }
func (m *MinionConfig) String() string            { return proto.CompactTextString(m) }
func (*MinionConfig) ProtoMessage()               {}
func (*MinionConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Reply struct {
	Success bool   `protobuf:"varint,1,opt,name=Success" json:"Success,omitempty"`
	Error   string `protobuf:"bytes,2,opt,name=Error" json:"Error,omitempty"`
}

func (m *Reply) Reset()                    { *m = Reply{} }
func (m *Reply) String() string            { return proto.CompactTextString(m) }
func (*Reply) ProtoMessage()               {}
func (*Reply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Request struct {
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func init() {
	proto.RegisterType((*MinionConfig)(nil), "MinionConfig")
	proto.RegisterType((*Reply)(nil), "Reply")
	proto.RegisterType((*Request)(nil), "Request")
	proto.RegisterEnum("MinionConfig_Role", MinionConfig_Role_name, MinionConfig_Role_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// Client API for Minion service

type MinionClient interface {
	SetMinionConfig(ctx context.Context, in *MinionConfig, opts ...grpc.CallOption) (*Reply, error)
	GetMinionConfig(ctx context.Context, in *Request, opts ...grpc.CallOption) (*MinionConfig, error)
}

type minionClient struct {
	cc *grpc.ClientConn
}

func NewMinionClient(cc *grpc.ClientConn) MinionClient {
	return &minionClient{cc}
}

func (c *minionClient) SetMinionConfig(ctx context.Context, in *MinionConfig, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := grpc.Invoke(ctx, "/Minion/SetMinionConfig", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minionClient) GetMinionConfig(ctx context.Context, in *Request, opts ...grpc.CallOption) (*MinionConfig, error) {
	out := new(MinionConfig)
	err := grpc.Invoke(ctx, "/Minion/GetMinionConfig", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Minion service

type MinionServer interface {
	SetMinionConfig(context.Context, *MinionConfig) (*Reply, error)
	GetMinionConfig(context.Context, *Request) (*MinionConfig, error)
}

func RegisterMinionServer(s *grpc.Server, srv MinionServer) {
	s.RegisterService(&_Minion_serviceDesc, srv)
}

func _Minion_SetMinionConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(MinionConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(MinionServer).SetMinionConfig(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Minion_GetMinionConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(MinionServer).GetMinionConfig(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _Minion_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Minion",
	HandlerType: (*MinionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetMinionConfig",
			Handler:    _Minion_SetMinionConfig_Handler,
		},
		{
			MethodName: "GetMinionConfig",
			Handler:    _Minion_GetMinionConfig_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor0 = []byte{
	// 256 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x5c, 0x90, 0xdf, 0x4a, 0xc3, 0x30,
	0x14, 0xc6, 0xdb, 0x9a, 0x76, 0xed, 0x71, 0xb3, 0x33, 0x57, 0x61, 0x57, 0x23, 0x37, 0x0e, 0x91,
	0x08, 0xf3, 0x09, 0x44, 0x8b, 0x0c, 0xd9, 0x1f, 0xd2, 0x81, 0xd7, 0xb6, 0x1e, 0xa5, 0x38, 0x9a,
	0x98, 0x66, 0x82, 0xaf, 0xe2, 0xd3, 0x9a, 0x06, 0x2f, 0xac, 0x77, 0xe7, 0x9c, 0x9c, 0xdf, 0x97,
	0xef, 0x3b, 0x70, 0xaa, 0xab, 0x6b, 0x5d, 0x09, 0x6d, 0x94, 0x55, 0xfc, 0x3b, 0x84, 0xf1, 0xba,
	0x69, 0x1b, 0xd5, 0xde, 0xa9, 0xf6, 0xb5, 0x79, 0xa3, 0x00, 0xd1, 0xea, 0x9e, 0x85, 0xf3, 0x70,
	0x91, 0xd1, 0x39, 0x10, 0xa3, 0x0e, 0xc8, 0x22, 0xd7, 0x9d, 0x2d, 0xa9, 0xf8, 0xbb, 0x28, 0xa4,
	0x7b, 0xa1, 0xe7, 0x90, 0xed, 0x4c, 0xf3, 0xf9, 0x6c, 0x71, 0xb5, 0x63, 0x27, 0x1e, 0x72, 0xa3,
	0xc2, 0xd6, 0x2f, 0x7b, 0xf5, 0x8e, 0x2d, 0x23, 0x7e, 0x34, 0x06, 0x52, 0x6a, 0xac, 0x59, 0xdc,
	0x77, 0x7c, 0x01, 0xc4, 0xb3, 0x29, 0x90, 0xcd, 0x76, 0x53, 0x4c, 0x03, 0xf7, 0x67, 0xf2, 0xb4,
	0x95, 0x8f, 0x85, 0x9c, 0x86, 0x7d, 0xbd, 0xbe, 0x2d, 0xf7, 0xae, 0x8e, 0xf8, 0x05, 0xc4, 0x12,
	0xf5, 0xe1, 0x8b, 0xe6, 0x30, 0x2a, 0x8f, 0x75, 0x8d, 0x5d, 0xe7, 0x9d, 0xa5, 0x74, 0x02, 0x71,
	0x61, 0x8c, 0x32, 0xde, 0x5a, 0xc6, 0x33, 0x18, 0x49, 0xfc, 0x38, 0x62, 0x67, 0x97, 0x95, 0xe3,
	0xbd, 0x4d, 0x7a, 0x09, 0x79, 0x89, 0x76, 0x10, 0x6e, 0x32, 0x88, 0x30, 0x4b, 0x84, 0x97, 0xe7,
	0x01, 0xbd, 0x82, 0xfc, 0xe1, 0xdf, 0x6e, 0x2a, 0x7e, 0x25, 0x67, 0x43, 0x8a, 0x07, 0x55, 0xe2,
	0x6f, 0x77, 0xf3, 0x13, 0x00, 0x00, 0xff, 0xff, 0xeb, 0x03, 0x32, 0x2b, 0x4a, 0x01, 0x00, 0x00,
}
