#!/bin/bash

# This script checks if there's anything in the minion logs referencing containers
# that failed to boot

if docker logs minion |& grep 'Failed to start container' > /dev/null ; then
    echo "Some containers failed to start: $(docker logs minion |& grep 'Failed to start container' | cut -d' ' -f7 | cut -d':' -f1 | sort | uniq)"
    exit 1
fi
exit 0
