#!/bin/bash

# This script checks if there's anything in the minion logs referencing containers
# that failed to boot

if docker logs minion |& grep 'ERROR' > /dev/null ; then
    echo "Error log messages: $(docker logs minion | grep 'ERROR')"
    exit 1
fi
exit 0
