#!/bin/bash

echo "=============================== Minion ================================="
docker logs minion

echo "\n\n"
echo "=============================== Etcd ==================================="
docker logs etcd

echo "\n\n"
echo "=============================== Swarm =================================="
docker logs swarm

echo "\n\n"
echo "=============================== ovs-vswitchd ==========================="
docker logs ovs-vswitchd

echo "\n\n"
echo "=============================== ovsdb-server ==========================="
docker logs ovsdb-server

echo "\n\n"
echo "=============================== ovn-controller ========================="
docker logs ovn-controller

echo "\n\n"
echo "=============================== ovn-northd ============================="
docker logs ovn-northd

exit 0
