// Code generated by protoc-gen-go.
// source: proto.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	proto.proto

It has these top-level messages:
	MinionConfig
	Reply
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type MinionConfig_Role int32

const (
	MinionConfig_MASTER MinionConfig_Role = 0
	MinionConfig_WORKER MinionConfig_Role = 1
)

var MinionConfig_Role_name = map[int32]string{
	0: "MASTER",
	1: "WORKER",
}
var MinionConfig_Role_value = map[string]int32{
	"MASTER": 0,
	"WORKER": 1,
}

func (x MinionConfig_Role) String() string {
	return proto1.EnumName(MinionConfig_Role_name, int32(x))
}
func (MinionConfig_Role) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type MinionConfig struct {
	EtcdToken string            `protobuf:"bytes,1,opt,name=EtcdToken" json:"EtcdToken,omitempty"`
	PrivateIP string            `protobuf:"bytes,2,opt,name=PrivateIP" json:"PrivateIP,omitempty"`
	Role      MinionConfig_Role `protobuf:"varint,3,opt,name=role,enum=MinionConfig_Role" json:"role,omitempty"`
}

func (m *MinionConfig) Reset()                    { *m = MinionConfig{} }
func (m *MinionConfig) String() string            { return proto1.CompactTextString(m) }
func (*MinionConfig) ProtoMessage()               {}
func (*MinionConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Reply struct {
	Success bool   `protobuf:"varint,1,opt,name=Success" json:"Success,omitempty"`
	Error   string `protobuf:"bytes,2,opt,name=Error" json:"Error,omitempty"`
}

func (m *Reply) Reset()                    { *m = Reply{} }
func (m *Reply) String() string            { return proto1.CompactTextString(m) }
func (*Reply) ProtoMessage()               {}
func (*Reply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto1.RegisterType((*MinionConfig)(nil), "MinionConfig")
	proto1.RegisterType((*Reply)(nil), "Reply")
	proto1.RegisterEnum("MinionConfig_Role", MinionConfig_Role_name, MinionConfig_Role_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// Client API for Minion service

type MinionClient interface {
	SetMinionConfig(ctx context.Context, in *MinionConfig, opts ...grpc.CallOption) (*Reply, error)
}

type minionClient struct {
	cc *grpc.ClientConn
}

func NewMinionClient(cc *grpc.ClientConn) MinionClient {
	return &minionClient{cc}
}

func (c *minionClient) SetMinionConfig(ctx context.Context, in *MinionConfig, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := grpc.Invoke(ctx, "/.Minion/SetMinionConfig", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Minion service

type MinionServer interface {
	SetMinionConfig(context.Context, *MinionConfig) (*Reply, error)
}

func RegisterMinionServer(s *grpc.Server, srv MinionServer) {
	s.RegisterService(&_Minion_serviceDesc, srv)
}

func _Minion_SetMinionConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(MinionConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(MinionServer).SetMinionConfig(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _Minion_serviceDesc = grpc.ServiceDesc{
	ServiceName: ".Minion",
	HandlerType: (*MinionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetMinionConfig",
			Handler:    _Minion_SetMinionConfig_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor0 = []byte{
	// 196 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x03, 0x93, 0x4a, 0x65, 0x5c, 0x3c, 0xbe, 0x99, 0x79, 0x99, 0xf9, 0x79, 0xce, 0xf9,
	0x79, 0x69, 0x99, 0xe9, 0x42, 0x82, 0x5c, 0x9c, 0xae, 0x25, 0xc9, 0x29, 0x21, 0xf9, 0xd9, 0xa9,
	0x79, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x20, 0xa1, 0x80, 0xa2, 0xcc, 0xb2, 0xc4, 0x92, 0x54,
	0xcf, 0x00, 0x09, 0x26, 0xb0, 0x90, 0x02, 0x17, 0x4b, 0x51, 0x7e, 0x4e, 0xaa, 0x04, 0x33, 0x90,
	0xc7, 0x67, 0x24, 0xa4, 0x87, 0x6c, 0x84, 0x5e, 0x10, 0x50, 0x46, 0x49, 0x8e, 0x8b, 0x05, 0x44,
	0x0b, 0x71, 0x71, 0xb1, 0xf9, 0x3a, 0x06, 0x87, 0xb8, 0x06, 0x09, 0x30, 0x80, 0xd8, 0xe1, 0xfe,
	0x41, 0xde, 0x40, 0x36, 0xa3, 0x92, 0x3a, 0x17, 0x6b, 0x50, 0x6a, 0x41, 0x4e, 0xa5, 0x10, 0x3f,
	0x17, 0x7b, 0x70, 0x69, 0x72, 0x72, 0x6a, 0x71, 0x31, 0xd8, 0x3a, 0x0e, 0x21, 0x5e, 0x2e, 0x56,
	0xd7, 0xa2, 0xa2, 0xfc, 0x22, 0x88, 0x55, 0x46, 0x26, 0x40, 0x03, 0xc0, 0xa6, 0x0b, 0x69, 0x71,
	0xf1, 0x07, 0xa7, 0x96, 0xa0, 0xb8, 0x96, 0x17, 0xc5, 0x66, 0x29, 0x36, 0x3d, 0xb0, 0x99, 0x4a,
	0x0c, 0x49, 0x6c, 0x60, 0xdf, 0x19, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x60, 0x3a, 0x2b, 0xbd,
	0xec, 0x00, 0x00, 0x00,
}
