// Code generated by protoc-gen-go.
// source: proto.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	proto.proto

It has these top-level messages:
	MinionConfig
	Reply
	Request
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type MinionConfig_Role int32

const (
	MinionConfig_NONE   MinionConfig_Role = 0
	MinionConfig_MASTER MinionConfig_Role = 1
	MinionConfig_WORKER MinionConfig_Role = 2
)

var MinionConfig_Role_name = map[int32]string{
	0: "NONE",
	1: "MASTER",
	2: "WORKER",
}
var MinionConfig_Role_value = map[string]int32{
	"NONE":   0,
	"MASTER": 1,
	"WORKER": 2,
}

func (x MinionConfig_Role) String() string {
	return proto1.EnumName(MinionConfig_Role_name, int32(x))
}
func (MinionConfig_Role) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type MinionConfig struct {
	ID        string            `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
	Role      MinionConfig_Role `protobuf:"varint,2,opt,name=role,enum=MinionConfig_Role" json:"role,omitempty"`
	PrivateIP string            `protobuf:"bytes,3,opt,name=PrivateIP" json:"PrivateIP,omitempty"`
	EtcdToken string            `protobuf:"bytes,4,opt,name=EtcdToken" json:"EtcdToken,omitempty"`
}

func (m *MinionConfig) Reset()                    { *m = MinionConfig{} }
func (m *MinionConfig) String() string            { return proto1.CompactTextString(m) }
func (*MinionConfig) ProtoMessage()               {}
func (*MinionConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Reply struct {
	Success bool   `protobuf:"varint,1,opt,name=Success" json:"Success,omitempty"`
	Error   string `protobuf:"bytes,2,opt,name=Error" json:"Error,omitempty"`
}

func (m *Reply) Reset()                    { *m = Reply{} }
func (m *Reply) String() string            { return proto1.CompactTextString(m) }
func (*Reply) ProtoMessage()               {}
func (*Reply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Request struct {
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto1.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func init() {
	proto1.RegisterType((*MinionConfig)(nil), "MinionConfig")
	proto1.RegisterType((*Reply)(nil), "Reply")
	proto1.RegisterType((*Request)(nil), "Request")
	proto1.RegisterEnum("MinionConfig_Role", MinionConfig_Role_name, MinionConfig_Role_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// Client API for Minion service

type MinionClient interface {
	SetMinionConfig(ctx context.Context, in *MinionConfig, opts ...grpc.CallOption) (*Reply, error)
	GetMinionConfig(ctx context.Context, in *Request, opts ...grpc.CallOption) (*MinionConfig, error)
}

type minionClient struct {
	cc *grpc.ClientConn
}

func NewMinionClient(cc *grpc.ClientConn) MinionClient {
	return &minionClient{cc}
}

func (c *minionClient) SetMinionConfig(ctx context.Context, in *MinionConfig, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := grpc.Invoke(ctx, "/.Minion/SetMinionConfig", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minionClient) GetMinionConfig(ctx context.Context, in *Request, opts ...grpc.CallOption) (*MinionConfig, error) {
	out := new(MinionConfig)
	err := grpc.Invoke(ctx, "/.Minion/GetMinionConfig", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Minion service

type MinionServer interface {
	SetMinionConfig(context.Context, *MinionConfig) (*Reply, error)
	GetMinionConfig(context.Context, *Request) (*MinionConfig, error)
}

func RegisterMinionServer(s *grpc.Server, srv MinionServer) {
	s.RegisterService(&_Minion_serviceDesc, srv)
}

func _Minion_SetMinionConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(MinionConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(MinionServer).SetMinionConfig(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Minion_GetMinionConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(MinionServer).GetMinionConfig(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _Minion_serviceDesc = grpc.ServiceDesc{
	ServiceName: ".Minion",
	HandlerType: (*MinionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetMinionConfig",
			Handler:    _Minion_SetMinionConfig_Handler,
		},
		{
			MethodName: "GetMinionConfig",
			Handler:    _Minion_GetMinionConfig_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor0 = []byte{
	// 245 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x03, 0x93, 0x4a, 0x3d, 0x8c, 0x5c, 0x3c, 0xbe, 0x99, 0x79, 0x99, 0xf9, 0x79, 0xce,
	0xf9, 0x79, 0x69, 0x99, 0xe9, 0x42, 0x5c, 0x5c, 0x4c, 0x9e, 0x2e, 0x12, 0x8c, 0x0a, 0x8c, 0x1a,
	0x9c, 0x42, 0x0a, 0x5c, 0x2c, 0x45, 0xf9, 0x39, 0xa9, 0x12, 0x4c, 0x40, 0x1e, 0x9f, 0x91, 0x90,
	0x1e, 0xb2, 0x42, 0xbd, 0x20, 0xa0, 0x8c, 0x90, 0x20, 0x17, 0x67, 0x40, 0x51, 0x66, 0x59, 0x62,
	0x49, 0xaa, 0x67, 0x80, 0x04, 0x33, 0x58, 0x13, 0x50, 0xc8, 0xb5, 0x24, 0x39, 0x25, 0x24, 0x3f,
	0x3b, 0x35, 0x4f, 0x82, 0x05, 0x24, 0xa4, 0xa4, 0xc1, 0xc5, 0x02, 0x56, 0xcd, 0xc1, 0xc5, 0xe2,
	0xe7, 0xef, 0xe7, 0x2a, 0xc0, 0x00, 0xb4, 0x85, 0xcd, 0xd7, 0x31, 0x38, 0xc4, 0x35, 0x48, 0x80,
	0x11, 0xc4, 0x0e, 0xf7, 0x0f, 0xf2, 0x06, 0xb2, 0x99, 0x94, 0xd4, 0xb9, 0x58, 0x83, 0x52, 0x0b,
	0x72, 0x2a, 0x85, 0xf8, 0xb9, 0xd8, 0x83, 0x4b, 0x93, 0x93, 0x53, 0x8b, 0x8b, 0xc1, 0x6e, 0xe1,
	0x10, 0xe2, 0xe5, 0x62, 0x75, 0x2d, 0x2a, 0xca, 0x2f, 0x02, 0x3b, 0x86, 0x53, 0x89, 0x93, 0x8b,
	0x3d, 0x28, 0xb5, 0xb0, 0x34, 0xb5, 0xb8, 0xc4, 0x28, 0x09, 0x68, 0x16, 0xd8, 0x61, 0x42, 0x5a,
	0x5c, 0xfc, 0xc1, 0xa9, 0x25, 0x28, 0xde, 0xe1, 0x45, 0x71, 0xb4, 0x14, 0x9b, 0x1e, 0xd8, 0x78,
	0x25, 0x06, 0x21, 0x1d, 0x2e, 0x7e, 0x77, 0x34, 0xb5, 0x1c, 0x7a, 0x50, 0x23, 0xa5, 0x50, 0x75,
	0x29, 0x31, 0x24, 0xb1, 0x81, 0x43, 0xcb, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xee, 0x48, 0x82,
	0xf4, 0x3c, 0x01, 0x00, 0x00,
}
