#!/bin/sh

case $1 in
        "ovs-vswitchd") ovs-vswitchd --pidfile \
            --log-file=/var/log/openvswitch/ovs-vswitchd.log
        ;;
        "ovn-controller") ovn-controller --pidfile \
            --log-file=/var/log/openvswitch/ovn-controller.log
        ;;
        "ovn-northd") ovn-northd --pidfile \
            --log-file=/var/log/openvswitch/ovn-northd.log
        ;;
        "ovsdb-server") ovsdb-server --pidfile\
            --remote=punix:/var/run/openvswitch/db.sock \
            --remote=ptcp:6640 \
            --remote=db:Open_vSwitch,Open_vSwitch,manager_options \
            --log-file=/var/log/openvswitch/ovsdb-server.log \
            /etc/openvswitch/conf.db \
            /etc/openvswitch/ovnnb.db \
            /etc/openvswitch/ovnsb.db
        ;;
        *) echo "$0 [ovs-vswitchd|ovsdb-server|ovn-controller|ovn-northd]"
esac
